openai_api_key: "OPENAI_API_KEY"
"
affiliation_links:
  - "https://www.amazon.fr/amazonprime?_encoding=UTF8&primeCampaignId=prime_assoc_ft?tag=zenzen0d-21France"
  - "https://www.amazon.fr/kindle-dbs/hz/signup?tag=https://www.amazon.fr/amazonprime?_encoding=UTF8&primeCampaignId=prime_assoc_ft?tag=zenzen0d-21France"
  - "https://www.amazon.fr/tbyb/huc?tag=zenzen0d-21France"
  - "https://go.fiverr.com/visit/?bta=1071918&brand=fiverrmarketplace"
  - "https://go.fiverr.com/visit/?bta=1071918&brand=fp"
  - "https://go.fiverr.com/visit/?bta=1071918&brand=logomaker"
article_length: 700
site_url: "https://kosmopol.github.io/SmartGen/"
social_tags: "#IA #Innovation #Tendances"
news_api_key: "e914db32b86b4c3cbb88930c97d60349"
