name: Auto Generate and Deploy

on:
  schedule:
    - cron: "0 0 * * *" # tous les jours à minuit UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install requests pyyaml jinja2

      - name: Generate Article
        run: python scripts/generate_article.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add content/posts/*.md
          git commit -m "Add new article [skip ci]" || echo "Rien à commit"
          git push

      # Build le site statique s'il y a un générateur (ici imaginons pas)
      # - name: Build site
      #   run: <commande>

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # si le site statique est à la racine
          # Sinon, build un dossier public

      - name: Post to Socials
        run: python scripts/post_to_socials.py
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
